[tools]
python = "3.10.16"
node = "20.11.0"
npm = "10.5.2"
java = "17"
uv = "0.7.19"
maven = "3.9.2"

[tasks.celery]
description = "Start Celery worker on Windows"
dir = ".\\python-service\\"
shell = "powershell"
run = """
uv run celery -A celery_worker worker --loglevel=info --pool=threads
"""

[tasks.python-api]
description = "Start Python FastAPI on Windows"
dir = ".\\python-service\\"
shell = "powershell"
run = """
uv run uvicorn main:app --reload
"""

[tasks.backend]
description = "Start Spring Boot Backend on Windows using Maven"
dir = ".\\backend-service\\"
shell = "powershell"
run = """
mvn spring-boot:run
"""

[tasks.backend-build-and-run]
description = "Build and run Spring Boot JAR"
dir = "backend-service"
shell = "powershell"
run = """
& mvn clean package
& java -jar .\\target\\demo-0.0.1-SNAPSHOT.jar
"""


[tasks.frontend]
description = "Start React Frontend on Windows"
dir = ".\\frontend-service\\"
shell = "powershell"
run = """
npm start
"""

